import CustomRootLayout from "@/components/layout/custom-root-layout";
import "./globals.css";

export const metadata = {
  title: "Maine Majesty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CustomRootLayout>
          {children}
        </CustomRootLayout>

      </body>
    </html>
  );
}
